// <auto-generated />
using System;
using FinMind.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinMind.Migrations
{
    [DbContext(typeof(FinMindDbContext))]
    [Migration("20260318191959_AjustarCategorias")]
    partial class AjustarCategorias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FinMind.Models.Enitdades.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Leida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("alertas", (string)null);
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Archivada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "Nombre")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.ConexionBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessToken")
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaExpiracionToken")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaSincronizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdConexionExterna")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Proveedor")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("conexiones_bancarias", (string)null);
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.ConfiguracionUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormatoExportacionPreferido")
                        .HasColumnType("int");

                    b.Property<bool>("NotificacionesActivas")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TamanoTexto")
                        .HasColumnType("int");

                    b.Property<int>("Tema")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("configuraciones_usuario", (string)null);
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.CuentaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BIC")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Banco")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid?>("ConexionBancariaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaSincronizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<string>("IdCuentaExterna")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("SaldoActual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConexionBancariaId")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("cuentas_bancarias", (string)null);
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.Exportacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Formato")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("exportaciones", (string)null);
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.SincronizacionBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConexionBancariaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("NumeroMovimientosImportados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConexionBancariaId");

                    b.ToTable("sincronizaciones_bancarias", (string)null);
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CuentaBancariaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdTransaccionExterna")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("Origen")
                        .HasColumnType("int");

                    b.Property<int>("Proveedor")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CuentaBancariaId");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.HasIndex("UsuarioId", "Origen", "IdTransaccionExterna");

                    b.ToTable("transacciones", (string)null);
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaCambioPassword")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MonedaPreferida")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.Alerta", b =>
                {
                    b.HasOne("FinMind.Models.Enitdades.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.Categoria", b =>
                {
                    b.HasOne("FinMind.Models.Enitdades.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.ConexionBancaria", b =>
                {
                    b.HasOne("FinMind.Models.Enitdades.Usuario", "Usuario")
                        .WithMany("ConexionesBancarias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.ConfiguracionUsuario", b =>
                {
                    b.HasOne("FinMind.Models.Enitdades.Usuario", "Usuario")
                        .WithOne("ConfiguracionUsuario")
                        .HasForeignKey("FinMind.Models.Enitdades.ConfiguracionUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.CuentaBancaria", b =>
                {
                    b.HasOne("FinMind.Models.Enitdades.ConexionBancaria", "ConexionBancaria")
                        .WithOne("CuentaBancaria")
                        .HasForeignKey("FinMind.Models.Enitdades.CuentaBancaria", "ConexionBancariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinMind.Models.Enitdades.Usuario", "Usuario")
                        .WithOne("CuentaBancaria")
                        .HasForeignKey("FinMind.Models.Enitdades.CuentaBancaria", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConexionBancaria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.Exportacion", b =>
                {
                    b.HasOne("FinMind.Models.Enitdades.Usuario", "Usuario")
                        .WithMany("Exportaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.SincronizacionBancaria", b =>
                {
                    b.HasOne("FinMind.Models.Enitdades.ConexionBancaria", "ConexionBancaria")
                        .WithMany("Sincronizaciones")
                        .HasForeignKey("ConexionBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConexionBancaria");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.Transaccion", b =>
                {
                    b.HasOne("FinMind.Models.Enitdades.Categoria", "Categoria")
                        .WithMany("Transacciones")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinMind.Models.Enitdades.CuentaBancaria", "CuentaBancaria")
                        .WithMany("Transacciones")
                        .HasForeignKey("CuentaBancariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinMind.Models.Enitdades.Usuario", "Usuario")
                        .WithMany("Transacciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("CuentaBancaria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.Categoria", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.ConexionBancaria", b =>
                {
                    b.Navigation("CuentaBancaria");

                    b.Navigation("Sincronizaciones");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.CuentaBancaria", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("FinMind.Models.Enitdades.Usuario", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Categorias");

                    b.Navigation("ConexionesBancarias");

                    b.Navigation("ConfiguracionUsuario");

                    b.Navigation("CuentaBancaria");

                    b.Navigation("Exportaciones");

                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
